### ISSUE TITLE
Crear UI de alta titular

### ISSUE THREAD

**Issue by BodeMatias** [Metodos-Agiles-UTN-2020/frontend#6]
Crear el formulario para agregar un titular al sistema.

Se requieren los siguientes datos:

- Tipo (Enum) y Nº de documento (Integer)
- Apellido (String) y Nombre (String)
- Fecha de nacimiento (Date)
- Dirección (String)
- Clase solicitada (A-G) (Enum)
- Grupo sanguíneo y factor RH (Enum)
- Donante de órganos (SI/NO) (Boolean)
- Foto del solicitante

**Comment by fbusso** [comment]
Duplicado de #3
